### PR TITLE
added get all records functionality

### PR DESCRIPTION
**Pull request by pk38**
Added this functionality to fetch all records from db for displaying job cards easily using promises.

### CODE REVIEW

**Review by r4sharma — APPROVED** [review]
Hi @pk38 ,
One of the tests is failing in database.test.js,

**Comment by pk38** [comment]
hi @r4sharma , corrected that test, pls approve again!

**Comment by r4sharma** [comment]
@pk38 Already approved🙂

**Comment by pk38** [comment]
@r4sharma thanks!

**Pull request merged**
